{"name": "test_add2[1-2-3]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 2\n +  where 4 = add(1, 3)", "trace": "self = <test_case.test_3.TestAbc object at 0x04DA4580>, a = 1, b = 2, c = 3\n\n    def test_add2(self,a,b,c):  # => 作为用例参数，接收装饰器传入的数据\n>       assert add(a, c) == b\nE       assert 4 == 2\nE        +  where 4 = add(1, 3)\n\ntest_case\\test_3.py:11: AssertionError"}, "parameters": [{"name": "a", "value": "1"}, {"name": "b", "value": "2"}, {"name": "c", "value": "3"}], "start": 1606560207787, "stop": 1606560207787, "uuid": "95806f90-1b9f-4cf8-8334-cf3ae2f86c39", "historyId": "6a5857a3430eef0778c3490ea742ce67", "testCaseId": "48dace7bcfa93fab0e591da0a625ef44", "fullName": "test_case.test_3.TestAbc#test_add2", "labels": [{"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_3"}, {"name": "subSuite", "value": "TestAbc"}, {"name": "host", "value": "DESKTOP-EQA5M9D"}, {"name": "thread", "value": "6592-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_3"}]}